### ISSUE TITLE
MAJOR ISSUE: No source for utilized backpropagation algorithm!

### ISSUE THREAD

**Issue by edfink234** [LinkedInLearning/training-neural-networks-in-cpp-4404365#1]
## Issue Overview

In the backpropagation part of the code [here](https://github.com/LinkedInLearning/training-neural-networks-in-cpp-4404365/blob/6665e2e4f2cbde762ee0ccc23e11bceb730f36e5/src/05_06/SDRNN_7to1/Source/MLP.cpp#L100-L107), there is no source or proof given for the formula used to compute the error terms of the neurons in the preceding layers, namely:

$`\mathrm{fwd_error} = \sum_{k \in \mathrm{outs}} w_{kh} \delta_k`$

## Describe your environment

N/A

## Steps to Reproduce

1. Look at code [here](https://github.com/LinkedInLearning/training-neural-networks-in-cpp-4404365/blob/6665e2e4f2cbde762ee0ccc23e11bceb730f36e5/src/05_06/SDRNN_7to1/Source/MLP.cpp#L100-L107).
2. Check to see if there is a source corroborating the utilized backpropagation algorithm. 
3. Realize that there is indeed no source corroborating the utilized backpropagation algorithm. 

## Expected Behavior

A source corroborating the utilized backpropagation algorithm.

## Current Behavior

No source was found.

## Possible Solution

Include a source.

## Screenshots / Video

Look [here](https://github.com/LinkedInLearning/training-neural-networks-in-cpp-4404365/blob/6665e2e4f2cbde762ee0ccc23e11bceb730f36e5/src/05_06/SDRNN_7to1/Source/MLP.cpp#L100-L107) please.

## Related Issues

N/A

**Comment by kuashio** [comment]
LinkedIn Learning courses don't usually cite sources for theoretical concepts. Please note that authors don't claim authorship for said concepts, they simply don't formally cite books, journals, or other sources. The neural networks taught in this course came mostly from the book "Artificial Intelligence: A Modern Approach" by Peter Norvig and Stuart Russell. This may be mentioned in the course videos.
